config/routes.rb
WhoAreMyPeeps::Application.routes.draw do
  resources :peeps

  root 'peeps#index'

end

app/models/peep.rb
class Peep < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  before_action :set_peep, only: [:show, :edit, :update, :destroy]

  # GET /peeps
  # GET /peeps.json
  def index
    @peeps = Peep.all
  end

  # GET /peeps/1
  # GET /peeps/1.json
  def show
  end

  # GET /peeps/new
  def new
    @peep = Peep.new
  end

  # GET /peeps/1/edit
  def edit
  end

  # POST /peeps
  # POST /peeps.json
  def create
    @peep = Peep.new(peep_params)

    respond_to do |format|
      if @peep.save
        format.html { redirect_to @peep, notice: 'Peep was successfully created.' }
        format.json { render action: 'show', status: :created, location: @peep }
      else
        format.html { render action: 'new' }
        format.json { render json: @peep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peeps/1
  # PATCH/PUT /peeps/1.json
  def update
    respond_to do |format|
      if @peep.update(peep_params)
        format.html { redirect_to @peep, notice: 'Peep was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @peep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peeps/1
  # DELETE /peeps/1.json
  def destroy
    @peep.destroy
    respond_to do |format|
      format.html { redirect_to peeps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peep
      @peep = Peep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peep_params
      params.require(:peep).permit(:name, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/peeps/_form.html.erb
<%= form_for(@peep) do |f| %>
  <% if @peep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peep.errors.count, "error") %> prohibited this peep from being saved:</h2>

      <ul>
      <% @peep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peeps/edit.html.erb
<h1>Editing peep</h1>

<%= render 'form' %>

<%= link_to 'Show', @peep %> |
<%= link_to 'Back', peeps_path %>

app/views/peeps/index.html.erb
<h1>Listing peeps (The Peeps Index)</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @peeps.each do |peep| %>
      <tr>
        <td><%= peep.name %></td>
        <td><%= peep.role %></td>
        <td><%= link_to 'Show', peep %></td>
        <td><%= link_to 'Edit', edit_peep_path(peep) %></td>
        <td><%= link_to 'Destroy', peep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peep', new_peep_path %>

app/views/peeps/new.html.erb
<h1>New peep (The 'New' Page)</h1>

<%= render 'form' %>

<%= link_to 'Back', peeps_path %>

app/views/peeps/show.html.erb
<p id="notice"><%= notice %></p>

<h1>The Peep 'show' page</h1>

<p>(get your mind out of the gutter)</p>

<p>
  <strong>Name:</strong>
  <%= @peep.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @peep.role %>
</p>

<%= link_to 'Edit', edit_peep_path(@peep) %> |
<%= link_to 'Back', peeps_path %>